WinWaitActive("Открыть")
Sleep(10000)
ControlClick("Открыть", "", "Edit1")
Sleep(500)
WinWaitActive("Открыть", "", 1)
Send("C:\Users\User\Documents\Photo{ENTER}")
Sleep(500)
Send("O_TGxQBcI5M{ENTER}")
WinWaitClose("Открыть", "", 1)